# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1418135346);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 24);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.search.isUS", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20141201171754");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20141201171754");
user_pref("browser.startup.homepage_override.mstone", "34.0.5");
user_pref("browser.uitour.treatment.srch-chg-action", "ViewPage");
user_pref("browser.uitour.treatment.srch-chg-treatment", "firstrun_otherDefault");
user_pref("browser.uitour.whitelist.add.260", "");
user_pref("browser.uitour.whitelist.add.340", "");
user_pref("browser.uitour.whitelist.add.341", "");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1418221557223");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1418135220486");
user_pref("datareporting.policy.firstRunTime", "1418135157223");
user_pref("datareporting.sessions.current.activeTicks", 11);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1935);
user_pref("datareporting.sessions.current.main", 132);
user_pref("datareporting.sessions.current.sessionRestored", 1262);
user_pref("datareporting.sessions.current.startTime", "1418135225497");
user_pref("datareporting.sessions.current.totalTime", 157);
user_pref("datareporting.sessions.currentIndex", 4);
user_pref("datareporting.sessions.previous.0", "{\"s\":1418135156601,\"a\":2,\"t\":10,\"c\":true,\"m\":133,\"fp\":1576,\"sr\":1647}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1418135174375,\"a\":1,\"t\":5,\"c\":true,\"m\":123,\"fp\":2121,\"sr\":1276}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1418135182643,\"a\":1,\"t\":3,\"c\":true,\"m\":103,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1418135209331,\"a\":1,\"t\":11,\"c\":true,\"m\":122,\"fp\":1079,\"sr\":1144}");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:34.0.5");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1417455395000,\"rdfTime\":1417455382000}}}]");
user_pref("extensions.lastAppVersion", "34.0.5");
user_pref("extensions.lastPlatformVersion", "34.0.5");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20141201171754");
user_pref("gecko.mstone", "34.0.5");
user_pref("loop.soft_start_ticket_number", 15014756);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1418135288);
user_pref("media.gmp-gmpopenh264.version", "1.1");
user_pref("media.gmp-manager.lastCheck", 1418135287);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1418135225);
user_pref("toolkit.telemetry.previousBuildID", "20141201171754");
